### ISSUE TITLE
Possible left handed support?

### ISSUE THREAD

**Issue by Hoshi82** [Ashok0/SystemShock-UEVR#1]
I know that inputs can be swapped inside the UEVR sadly it doesn't go along nicely with still having models , UI, etc. attached to the right controller.

It's a nightmare, at least for me, to find the correct meshes and stuff inside UEVR so I know it might a bit much to ask but would it be possible to have a left handed profile where not only controls are swapped but hooks and meshes also?

**Comment by Ashok0** [comment]
Unfortunately, I don't think what you are asking for is possible as the base game has no left hand support and there are no left hand models.

**Comment by ReverVR** [comment]
> I know that inputs can be swapped inside the UEVR sadly it doesn't go along nicely with still having models , UI, etc. attached to the right controller.
> 
> It's a nightmare, at least for me, to find the correct meshes and stuff inside UEVR so I know it might a bit much to ask but would it be possible to have a left handed profile where not only controls are swapped but hooks and meshes also?

Hi. For Left Hand Use in UEVR --> Input ---> Active Option Left Handed together Dpad Shifting option

Enjoy
